# Generated by Django 6.0.5 on 2026-05-17 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': '"events"."tag"',
            },
        ),
    ]
