# Generated by Django 6.0.5 on 2026-05-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_event_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
