# Generated by Django 6.0.5 on 2026-05-28 04:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_online_url_and_event_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
