# Generated by Django 6.0.5 on 2026-05-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_event_review'),
        ('events', '0009_add_thumbnail_urls_venue_coords'),
    ]

    operations = [
    ]
