# Generated by Django 6.0.5 on 2026-05-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_20260530_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(
                choices=[("physical", "Physical"), ("virtual", "Virtual"), ("hybrid", "Hybrid")],
                default="physical",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='overbooking_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='virtual_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
