# Generated by Django 6.0.5 on 2026-05-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_add_hybrid_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
